### ISSUE TITLE
Review of White Paper

### ISSUE THREAD

**Issue by TazNafRaz** [BrightID/BrightID-Docs#16]
While reading through the white paper (https://www.brightid.org/whitepaper), on page 7, the word "receive" (under the "Suspicious" heading) should be "received".  

On page 11, is there are reason that phrases like "seed group" are not underlined, when they are underlined (and linked) on other pages?  For example, "A seed dao member can define a region by adding people who have been observed to connect to seed group members."

On page 13, under Long Term Funding ... Is there a reason the words "sponsored" and "sponsorship" are in italics?  I don't recall use of this in other areas of the document (I could be wrong).  

On page 2 at the top, the following sentence needs to be re-worded.  It currently reads “The social graph itself can be used as a reference for many different services, but none of these services are in charge of the graph, nor be able to control the behavior of individual users.”  I suggest this is re-written as “The social graph itself can be used as a reference for many different services, but none of these services are in charge of the graph, nor are they able to control the behavior of individual users.”  “nor are they” is where I suggest the change.

On page 2 under Decentralized Network, suggest improving this sentence by using “not only, but also”.  It is currently written as “It is crucial for multiple independent parties to be able to use their own analysis methods on the same connection data, both to ensure that authority over verified identities does not fall under the control of any single entity, but also to allow the regular auditing of analysis methods by independent parties.”  Suggest the following use of the expression “not only, but also” -- “It is crucial for multiple independent parties to be able to use their own analysis methods on the same connection data, not only to ensure that authority over verified identities does not fall under the control of any single entity, but also to allow the regular auditing of analysis methods by independent parties.”

**Comment by adamstallard** [comment]
Thanks.  I accepted the grammar suggestion as they are clearly better.  I will leave the underlining and italics as-is for now.
