### ISSUE TITLE
Open the source of the gitbook

### ISSUE THREAD

**Issue by waldyrious** [BrightID/BrightID-Docs#17]
It's not clear to me why the contents of the gitbook (https://brightid.gitbook.io) are not open source. Could that be considered?

**Comment by adamstallard** [comment]
Great suggestion!  I just enabled synchronization with https://brightid.gitbook.io/brightid/ to the master branch of this repo.

**Comment by waldyrious** [comment]
Awesome, thanks! Can you please check if there's a setting to enable the display of edit links ("edit this page" or "improve this page"), or at least a footer/sidebar link to this repository, to make it more discoverable how people can contribute to the docs? 

Also, would it also be possible to open source the contents of the [Aura gitbook](https://brightid.gitbook.io/aura/) to a public repo?

**Comment by adamstallard** [comment]
> Also, would it also be possible to open source the contents of the [Aura gitbook](https://brightid.gitbook.io/aura/) to a public repo?

I just created a repo for Aura docs https://github.com/Meta-Node/Aura-Docs .  Thanks for the suggestion.  I agree there should be an "improve this guide" link that goes to the appropriate github repo.   Feel free to make a PR to add it, if you like.
